### ISSUE TITLE
Revise Dashboard

### ISSUE THREAD

**Issue by sfisque** [sfisque/eCactus-latticeware#21]
Dashboard needs more fields to be calculated and displayed according to UX treatment document

**Comment by sfisque** [comment]
this is #3 from spreadsheet

**Comment by sfisque** [comment]
UX working, need to provide query logic for metrics and better layout using primefaces datagrid

**Comment by sfisque** [comment]
UX done.  need to wire up new queries for data

**Comment by chrisjpounds** [comment]
We had discussed the left panel would show metrics of Returns Completed, Returns Late Internal and Returns Late Statutory.  You were concerned that that since the due dates could be free form, we could have a million combinations otherwise.

**Comment by sfisque** [comment]
make the dashboard controller @RequestScoped to force recalculation with each page refresh
