### ISSUE TITLE
Heat Map page needs some revision

### ISSUE THREAD

**Issue by sfisque** [sfisque/eCactus-latticeware#22]
new heat map page has more available realestate so we can expand the map dimensions

**Comment by sfisque** [comment]
rolling this into next sprint.  i did not get around to it.

**Comment by sfisque** [comment]
done via commit c577bbb831d17dd0b45db2e1cd6baaea6ef9a7eb

**Comment by chrisjpounds** [comment]
Still need Export to PDF
