### ISSUE TITLE
CJP #1 - Data Field Updates

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#25]
Update db fields per the attached.  Revised Files
[Exelon UI DB Field Mapping.xlsx](https://github.com/sfisque/eCactus-latticeware/files/4247971/Exelon.UI.DB.Field.Mapping.xlsx)
[eCactus Flowchart (2-24-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4247972/eCactus.Flowchart.2-24-20.xlsx)

**Comment by sfisque** [comment]
make linkage between Lawson and GL_Type easier to maintain

**Comment by sfisque** [comment]
add  State Tax ID, State Registration Date, State Active
to Filing Calendar Detail (and new return setup?)

**Comment by sfisque** [comment]
closing this after moving the targets into separate stories
