### ISSUE TITLE
CJP #3 - Home UI

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#26]
Make Home Screen look like corresponding tab in attached file.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202332/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
duplicate of #21
