### ISSUE TITLE
CJP #4 - Filing Calendar UI

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#27]
Make Filing Calendar look like tab in the attached spreadsheet.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202339/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
will split this story.  we will address the changes in columns in the view this sprint.

new story crafted to add in new bulk un/approval functionality

**Comment by sfisque** [comment]
secondary story is #72

**Comment by sfisque** [comment]
Filtering has changed in the new version of PrimeFaces. need to explicitly build custom filtering

**Comment by sfisque** [comment]
need to modify Return object to hold the reviewers from the CalendarEntry
update UX to echo the new values

**Comment by sfisque** [comment]
need to add new fields for Return Sub Type, Comment, Master Comment, Related Return
and UX treatment for them
