### ISSUE TITLE
CJP #5 - Filing Calendar Detail in UI

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#28]
Make Filing Calendar Detail in UI look like tab in attached spreadsheet.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202349/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
2 sets of changes.  will split this story.

this story will address new Subtype, related period, due date internal, due date statutory, ,approval/unapproval flagging, and commentary fields

a new story will be crafted to handle the new calculation section at the bottom right.

**Comment by sfisque** [comment]
secondary story is #71

**Comment by sfisque** [comment]
upon inspection, #71 is a duplicate of #66, #67 and #68.  will mark it as a duplicate

**Comment by sfisque** [comment]
adding Subtype to the scope of this story

**Comment by sfisque** [comment]
calendar also needs the two new date fields for internal and statutory due date, and added code to resync them when calendar is updated

**Comment by sfisque** [comment]
also need to split website into state and local website field.
