### ISSUE TITLE
CJP #6 - Workflow/Generate Returns

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#29]
Make Workflow/Generate Returns
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202354/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like tab in attached spreadsheet.

**Comment by sfisque** [comment]
does not require changes, just verify still works with new schema/model changes

**Comment by sfisque** [comment]
tested
