### ISSUE TITLE
CJP #7 - Workflow/Import

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#30]
Make Workflow/Import
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202359/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like tab in attached spreadsheet.

**Comment by sfisque** [comment]
this has been handled.  the underlying functionality for the new imports is covered in different stories.
