### ISSUE TITLE
CJP #8 Workflow/Lock Returns

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#31]
Make Workflow/Lock Returns in UI look like corresponding worksheet in this file.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202361/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
no changes, just need to verify works with new database schema/model changes

**Comment by sfisque** [comment]
tested

**Comment by chrisjpounds** [comment]
Lock Returns takes me to a white screen
