### ISSUE TITLE
CJP #9 - Master Data Management Master Calendar

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#32]
Make Master Calendar in UI look like corresponding worksheet in this file.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202376/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
change column layout and verify user input operates properly
