### ISSUE TITLE
CJP #10 - Master Calendar Detail

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#33]
Make Master Data Management/Master Calendar Detail
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202378/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like corresponding worksheet in this file.

**Comment by sfisque** [comment]
adjust columns in table

**Comment by sfisque** [comment]
Edit icon click does not work
wire up support for Reviewer 1-3
fix lawson account editor
