### ISSUE TITLE
CJP #11 - New Return Setup

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#34]
Make Master Data Management/New Return Setup in UI look like corresponding worksheet in this file.  Revised to include Department ID.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-24-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4248005/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-24-20.xlsx)

**Comment by sfisque** [comment]
UX Redesign
add new "Comment" field, Related Return, Related Period

verify "Dept. ID" (what is this?), Payee Name (what is this?), Website (what is this?)

**Comment by sfisque** [comment]
still need to link up new fields (Return Subtype, Related Return, Related Period, Payee Name, Website, Reviewer 1-3, Dept ID, and Master Comment)

**Comment by sfisque** [comment]
almost done, still need to fix preparer/reviewer selectors (filter by role), and add new columns/attributes to schema/model for:   website, return subtype, 1->N reviewers, and master comment.
