### ISSUE TITLE
CJP #12 - MDM/Entity

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#35]
Make Master Data Management/Entity in UI look like corresponding worksheet in this file.

Also, key note: Many BU's to One Company Name Relationship

Revised.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-24-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4247981/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-24-20.xlsx)

**Comment by sfisque** [comment]
requires cosmetic mods to view

**Comment by sfisque** [comment]
requires adding 4 columns ( bank account , operating unit, project, and currency)
and removing corpFiveBytes.

**Comment by sfisque** [comment]
addressed by above commits

**Comment by chrisjpounds** [comment]
INCOMPLETE – Field Names do not line up to masks.  Confirmed we can have a many BU to one company name, which is good.
