### ISSUE TITLE
CJP #13 Account_Subaccount

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#36]
Make MDM/Account_Subaccount
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202389/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like corresponding worksheet in this file.

**Comment by sfisque** [comment]
requires cosmetic changes to GL Account view

**Comment by sfisque** [comment]
will require a new view and controller logic to handle parent/child relationship

**Comment by sfisque** [comment]
requires a new column (subaccount)

**Comment by chrisjpounds** [comment]
INCOMPLETE – Lawson Account should say Account.  accountSubAccount should say SubAccount
