### ISSUE TITLE
CJP #14 - MDM/Bank Holiday

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#37]
Make MDM/Bank Holiday
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202395/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like corresponding worksheet in this file.

**Comment by sfisque** [comment]
involves collapsing the PR holiday and holiday table into 1 table and collapse support code to match

**Comment by sfisque** [comment]
also requires adding dominion column to the schema/model

**Comment by sfisque** [comment]
fixed by the above commits

**Comment by chrisjpounds** [comment]
INCOMPLETE – Lawson Account should say Account.  accountSubAccount should say SubAccount.

**Comment by sfisque** [comment]
Bank Holiday does not feature Lawson Accounts
