### ISSUE TITLE
CJP #15 - MDM/Mailing Address

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#38]
Make MDM/Mailing Address
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202396/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like corresponding worksheet in this file.

**Comment by sfisque** [comment]
this should already be addressed by previous Master Data revision

**Comment by chrisjpounds** [comment]
Has superflous fields of email address and administrator.  Missing ACH Code.

**Comment by chrisjpounds** [comment]
Missing some address fields
