### ISSUE TITLE
CJP #16 - MDM/Filing Frequency

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#39]
Make MDM/Filing Frequency
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202401/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like corresponding worksheet in this file.

**Comment by sfisque** [comment]
this should already be addressed by previous Master Data revision
