### ISSUE TITLE
CJP #17 - MDM/Anybill

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#40]
Make MDM/Anybill
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202403/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like corresponding worksheet in this file.

**Comment by sfisque** [comment]
requires cosmetic mods to view

**Comment by sfisque** [comment]
addressed by commit 63c71ff9e65c8f799f0b01bab882fd1bbdca81f9
