### ISSUE TITLE
CJP #18 MDM/State

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#41]
Make MDM/State
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202410/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like corresponding worksheet in this file.

**Comment by sfisque** [comment]
need to rename "Providence" to "Country" to complete

**Comment by sfisque** [comment]
addressed in 0952bcf6fa3871cebcc6ffe65324ff6ca88e4af7
