### ISSUE TITLE
CJP #19 - MDM/Local

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#42]
Make MDM/Local
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202412/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)
 in UI look like corresponding worksheet in this file.

**Comment by sfisque** [comment]
this should already be addressed by previous Master Data revision
