### ISSUE TITLE
CJP #20 - MDM/Return Type

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#43]
Make MDM/Return Type in UI look like corresponding worksheet in this file.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202418/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
has a dependency on the new return subtype table creation

**Comment by sfisque** [comment]
current implementation needs to incorporate the new return subtype.  this may create some interesting changes due to the views being "atomic" and not "combined"

probably need a new view to handle this specific setup

**Comment by sfisque** [comment]
have decided to split the view to keep it within the current framework.  if it becomes "an issue" it can be combined at a later date.

**Comment by sfisque** [comment]
addressed by commit 7b92c0da1c84383759e45700222eba66550c0237
