### ISSUE TITLE
CJP #21 - Reports

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#44]
Make Reports Type in UI look like corresponding worksheet in this file.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202421/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
duplicate of #7
