### ISSUE TITLE
CJP #22 - Reports/Preparer Status

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#45]
Generate Report as laid out in the appropriate tab in the attached spreadsheet.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202438/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
with reversion of the report UX, there is nothing to do here.
