### ISSUE TITLE
CJP #23 Electronic Payments

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#46]
Generate Report as laid out in the appropriate tab in the attached spreadsheet.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202442/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
still need to do CSV and PDF output.  verify if we need UI for this one (it never had a true UI previously other than year/month selector on export page)

**Comment by sfisque** [comment]
this report never had CSV or PDF output, so i'm splitting that functionality off into a separate story
