### ISSUE TITLE
CJP #24 Reports - Electronic Payments with GL Detail

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#47]
Generate Report as laid out in the appropriate tab in the attached spreadsheet.  Revised - Rename to Journal Entry Report and follow the logic and layout in the attached file.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-24-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4247989/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-24-20.xlsx)

**Comment by sfisque** [comment]
Electronic Payments with GL Detail (#47) = Journal Entry in the spreadsheet
