### ISSUE TITLE
Reports G/L Extract - P3

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#48]
Generate Report as laid out in the appropriate tab in the attached spreadsheet.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202446/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
Reports G/L Extract (#48) = G/L Report in the spreadsheet
