### ISSUE TITLE
CJP #26 Reports-Heatmap

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#49]
Move Heatmap to Reports menu
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202450/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
this is out of scope.  Heat Map moved back to main menubar because it did not fit the reporting semantics (UI must be rendered before PDF can be generated)
