### ISSUE TITLE
Reports/Trend Analysis

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#50]
Generate Report as laid out in the appropriate tab in the attached spreadsheet.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202452/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
jim is working on the SQL part of this

**Comment by sfisque** [comment]
- [ ] verify scripts from Chris/Jim

**Comment by sfisque** [comment]
ran scripts.  import ran fine, scripts for report generation failed with errors.  emailed chris/scott with error messages

**Comment by sfisque** [comment]
need to add export buttons at bottom
