### ISSUE TITLE
CJP #28 - Reports/Anybill

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#51]
Generate Report as laid out in the appropriate tab in the attached spreadsheet.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202457/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
mostly done, still waiting on feedback on two columns
