### ISSUE TITLE
#30 - Reports EFT Journal Date

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#53]
Generate Report as laid out in the appropriate tab in the attached spreadsheet.

[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202471/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
Reports EFT Journal Date ($53) = Electronic Payments Summary in spreadsheet
