### ISSUE TITLE
#31 - Administration/Manage Users

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#54]
Make Administration/Manage Users in UI look like the tab in the attached worksheet.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202479/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
some UX mods based on user -> role mapping changes

**Comment by sfisque** [comment]
revisions include : singular role assignment (drop down)
fix for creation (seems to be "1 behind")

may move "temporary password" support to later sprint

**Comment by sfisque** [comment]
addressed by commit # 4a3400118c898802383a6284711836111de3549f

**Comment by chrisjpounds** [comment]
Edits and New users functionality does not appear to be updating
