### ISSUE TITLE
CJP #32 - Locals Filter

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#55]
Change   from a dropdown to a text box. Filter on "contains" any word in   text box

**Comment by sfisque** [comment]
this should already be addressed by previous revisions to Calendar views

**Comment by chrisjpounds** [comment]
Filtering in Filing Calendar not working

**Comment by sfisque** [comment]
that's less than helpful.  i just tested it and they all work.  is there a specific case (particular sequence of events, or a specific return entry) where the failure occurs?

in the future, please be more specific with details when indicating "it does not work".
