### ISSUE TITLE
CJP #34 Import Non-Vertex Report

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#57]
Be able to import Filing Calendar data from Non-Vertex Source in the attached format.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202485/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment]
This is the import referred to as "Whitepaper File" import
