### ISSUE TITLE
Weekly Notifications

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#63]
Users get automated weekly emails with outstanding tasks assigned to them (open returns)

**Comment by sfisque** [comment]
Please find the status report for the week of 6/8/2020. Please ensure timely sign-off of all filings in eCalendar
 
Late (Past Due)                           10
Coming Due (within 5 days)       15
Coming Due (within 10 days)      76
Completed                                  112
 
Link to eCalendar: https://nyarlathotep.latticeware.com:7002/eCactus/pages/home.xhtml

**Comment by sfisque** [comment]
testing remains

**Comment by sfisque** [comment]
testing to see if converting from singleton to stateless solves the immutable scheduling

**Comment by sfisque** [comment]
finalized version committed to git
