### ISSUE TITLE
CJP #41 - Bulk Sign Off

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#64]
From filing calendar, users can select all when datestamping Prepared, Reviewed, or unapproving returns.

**Comment by sfisque** [comment]
splitting out "Bulk Review" because that has multiple issues involved and it is non-trivial

**Comment by sfisque** [comment]
creating a new story for "bulk approval" and "bulk prepare" because they are non-trivial enhancements
