### ISSUE TITLE
Reporting Menu needs to be collapsed into single button

### ISSUE THREAD

**Issue by sfisque** [sfisque/eCactus-latticeware#7]
Reporting Menu needs to be changed to a single Button.

The separate reporting screens need to be refactored into a simple report generation selector screen

**Comment by sfisque** [comment]
done via above commit

**Comment by chrisjpounds** [comment]
INCOMPLETE.  Unable to directly download from main Reporting Screen.  Need to click on UI and then download.

**Comment by sfisque** [comment]
not incomplete.  there are separate stories for each of the report types.  this story is about changing the navigation.
